name: bubble_v2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
    - family: PretendardLight
      fonts:
        - asset: assets/fonts/Pretendard-Light.otf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf